"""Storage protocols. Local impls in local.py; cloud (R2 + Postgres) in cloud.py (D-2).

BlobStore is path-oriented because the pipeline uses libraries that read/write
real files (ifcopenshell, numpy, trimesh, FastAPI FileResponse). The local
backend maps keys straight to disk; a cloud backend stages to a local cache and
uploads on `commit` / `commit_dir`.
"""

from __future__ import annotations

from pathlib import Path
from typing import IO, Protocol


class BlobStore(Protocol):
    def exists(self, key: str) -> bool: ...
    def read_path(self, key: str) -> Path | None: ...
    def write_path(self, key: str) -> Path: ...
    def write_text(self, key: str, text: str) -> None: ...
    def write_stream(self, key: str, fileobj: IO) -> None: ...
    def read_text(self, key: str) -> str | None: ...
    def commit(self, key: str) -> None: ...
    def read_dir(self, prefix: str) -> Path | None: ...
    def write_dir(self, prefix: str) -> Path: ...
    def commit_dir(self, prefix: str) -> None: ...
    def delete_prefix(self, prefix: str) -> None: ...


class MetaStore(Protocol):
    def init(self) -> None: ...
    def clear_preparing(self) -> None:
        """Reset floors stuck in 'preparing' (from a crashed/redeployed process)."""
        ...

    def insert_model(self, model_id: str, filename: str, storey_count: int, unit_scale: float) -> None: ...
    def get_model(self, model_id: str) -> dict | None: ...
    def list_models(self) -> list[dict]: ...
    def delete_model(self, model_id: str) -> None: ...

    def set_floor_status(self, model_id: str, floor: int, status: str, *,
                         stage: str = "", pct: int = 0,
                         resolution: float | None = None, error: str = "") -> None: ...
    def get_floor_prep(self, model_id: str, floor: int) -> dict | None: ...

    def insert_route(self, route_id: str, model_id: str, floor: int, mode: str,
                     total_length: float, segment_count: int) -> None: ...
    def get_route(self, route_id: str) -> dict | None: ...
    def list_routes_for_model(self, model_id: str) -> list[dict]: ...
    def delete_route(self, route_id: str) -> None: ...
